In [53]:
import pandas as pd

caminho = '/content/drive/MyDrive/Ciencia de Dados/dados_pessoas.xlsx'
arquivo = pd.read_excel(caminho)

# 1. Funções de Estatísticas
def calcular_media_idade(df):
    return df['Idade'].mean()

def calcular_menor_peso(df):
    return df['Peso'].min()

def calcular_maior_altura(df):
    return df['Altura'].max()

media_idade = calcular_media_idade(arquivo)
menor_peso = calcular_menor_peso(arquivo)
maior_altura = calcular_maior_altura(arquivo)

print(f'Média de Idade: {media_idade:.2f}')
print(f'Menor Peso: {menor_peso}')
print(f'Maior Altura: {maior_altura}')

# 2. Cálculo do IMC e Categoria Dominante
imcs = []
for i in range(len(arquivo)):
    imc = arquivo['Peso'][i] / (arquivo['Altura'][i] ** 2)
    imcs.append(imc)

arquivo['IMC'] = imcs
arquivo.to_excel('/content/drive/MyDrive/Ciencia de Dados/dados_pessoas.xlsx')

def verificar_contagem_detalhada(df):
    categorias = []
    for imc in df['IMC']:
        if imc < 18.5: categorias.append('Abaixo do peso')
        elif imc < 25: categorias.append('Normal')
        elif imc < 30: categorias.append('Sobrepeso')
        else: categorias.append('Obeso')

    contagem = pd.Series(categorias).value_counts()
    return contagem



display(verificar_contagem_detalhada(arquivo))
dominante = verificar_contagem_detalhada(arquivo)
print(f'A categoria de IMC dominante é: {dominante.idxmax()}')
arquivo.describe()

Média de Idade: 38.65
Menor Peso: 52.7
Maior Altura: 1.89

Normal            10
Sobrepeso          6
Abaixo do peso     4
Name: count, dtype: int64

A categoria de IMC dominante é: Normal

           Idade       Peso     Altura        IMC
count  20.000000  20.000000  20.000000  20.000000
mean   38.650000  69.800000   1.763000  22.581402
std    10.204617  10.334663   0.079147   3.850206
min    18.000000  52.700000   1.620000  16.712858
25%    33.250000  60.225000   1.707500  18.832748
50%    39.500000  68.900000   1.785000  23.211152
75%    45.500000  77.650000   1.820000  25.412330
max    59.000000  85.100000   1.890000  29.724981