In [18]:
import pandas as pd
arquivo = pd.read_excel('/content/drive/MyDrive/Ciência de dados/Aula3.xlsx')

In [24]:
int(arquivo['IDADE'].mean())

734

In [20]:
arquivo['PESO'].min()

50

In [25]:
float(arquivo['ALTURA'].max())

1.9

In [32]:
for c in range(0,20):
  pessoa = arquivo.iloc[c]
  imc  = pessoa['PESO'] / (pessoa['ALTURA']*pessoa['ALTURA'])
  if imc > 40:
    arquivo.loc[c, 'IMC'] = 'Obesidade Grau III'
  elif 35 <= imc <= 39.9:
    arquivo.loc[c, 'IMC'] = 'Obesidade Grau II'
  elif 30 <= imc <= 34.9:
    arquivo.loc[c, 'IMC'] = 'Obesidade Grau I'
  elif 25 <= imc <= 29.9:
    arquivo.loc[c, 'IMC'] = 'Sobrepeso'
  elif 18.6 <= imc <= 24.9:
    arquivo.loc[c, 'IMC'] = 'Peso Normal'
  else:
    arquivo.loc[c, 'IMC'] = 'Baixo peso'

arquivo['IMC']

0       Sobrepeso
1     Peso Normal
2     Peso Normal
3     Peso Normal
4     Peso Normal
5     Peso Normal
6       Sobrepeso
7     Peso Normal
8       Sobrepeso
9       Sobrepeso
10    Peso Normal
11    Peso Normal
12    Peso Normal
13    Peso Normal
14    Peso Normal
15      Sobrepeso
16    Peso Normal
17      Sobrepeso
18    Peso Normal
19    Peso Normal
Name: IMC, dtype: object

In [28]:
arquivo.to_excel('/content/drive/MyDrive/Ciência de dados/filosofos_imc.xlsx')

In [29]:
arquivo['IMC'].mode()

0    Peso Normal
Name: IMC, dtype: object