In [36]:
#ABRIR ARQUIVOS DE DADOS E LER
import pandas as pd
caminho = '/content/drive/MyDrive/Ciencia de Dados/pessoasMedidas.xlsx'
arquivo = pd.read_excel(caminho)
arquivo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    20 non-null     object
 1   Idade   20 non-null     int64
 2   Peso    20 non-null     float64
 3   Altura  20 non-null     float64
 4   IMC     20 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 932.0+ bytes

In [37]:
arquivo=arquivo.fillna(0)
arquivo.describe()

           Idade        Peso     Altura        IMC
count  20.000000   20.000000  20.000000  20.000000
mean   44.050000   72.925000   1.735500  24.488500
std    13.558742   15.235066   0.117897   6.076909
min    23.000000   54.700000   1.550000  16.570000
25%    32.500000   61.800000   1.652500  19.880000
50%    42.000000   65.350000   1.750000  23.610000
75%    55.750000   86.425000   1.842500  28.577500
max    64.000000  101.300000   1.900000  41.040000

In [38]:
arquivo=arquivo.fillna(0)

In [39]:
arquivo[['Nome', 'Idade', 'Peso', 'Altura']]

               Nome  Idade   Peso  Altura
0         Ana Silva     58   56.7    1.85
1       Bruno Costa     33   63.4    1.84
2      Carla Mendes     61   94.4    1.77
3    Diego Oliveira     55   75.3    1.56
4    Elena Ferreira     31   64.0    1.79
5     Felipe Santos     53   61.9    1.81
6     Gabriela Lima     52   75.2    1.73
7    Henrique Rocha     35   98.6    1.55
8   Isabela Martins     28   91.9    1.69
9      João Pereira     27   62.9    1.86
10      Karen Alves     24   55.6    1.59
11      Lucas Souza     40   86.2    1.87
12   Mariana Castro     64   77.6    1.60
13  Nicolas Barbosa     42   54.7    1.67
14     Olivia Nunes     58   87.1    1.89
15      Pedro Gomes     54   61.5    1.58
16   Rafaela Torres     60   63.7    1.67
17   Samuel Ribeiro     23  101.3    1.90
18    Tatiana Pinto     42   66.7    1.80
19   Victor Cardoso     41   59.8    1.69

In [40]:
media_idade = arquivo['Idade'].mean()
print(f"Média de idade: {media_idade:.1f} anos")

Média de idade: 44.0 anos

In [41]:
menor_peso = arquivo['Peso'].min()
print(f"Menor peso: {menor_peso} kg")

Menor peso: 54.7 kg

In [42]:
maior_altura = arquivo['Altura'].max()
print(f"Maior altura: {maior_altura} m")

Maior altura: 1.9 m

In [43]:
arquivo['IMC'] = arquivo['Peso'] / (arquivo['Altura'] ** 2)
arquivo['IMC'] = arquivo['IMC'].round(2)

print("\n", arquivo[['Nome', 'Peso', 'Altura', 'IMC']].head())

#salvar
arquivo.to_excel(caminho, index=False)

              Nome  Peso  Altura    IMC
0       Ana Silva  56.7    1.85  16.57
1     Bruno Costa  63.4    1.84  18.73
2    Carla Mendes  94.4    1.77  30.13
3  Diego Oliveira  75.3    1.56  30.94
4  Elena Ferreira  64.0    1.79  19.97